name: Test Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    
runs:
  using: "composite"
  steps:
    - name: Run test job
      run: mvn test
